### ISSUE TITLE
Week 01 - Day 4 - Mock Portoflio

### ISSUE THREAD

**Issue by mdewey** [TatyCat/assignments#4]
# A Portfolio

For your first weekend project, we're going to be starting work on a portfolio website that you can improve over the rest of your career.

![Mockup](https://raw.githubusercontent.com/tiy-tpa-fee/assignments/master/portfolio/mockup.png)

You can find image assets you'll need here:

> https://github.com/tiy-tpa-fee/assignments/tree/master/portfolio/assets

The font used is [Roboto](https://fonts.google.com/specimen/Roboto).

Also, feel free to change it from Jason's picture to a picture of yourself.

## Objectives

- Build on your knowledge of HTML & CSS
- Implement, from scratch, a given design
- Use flexbox techniques layout pages.

## Requirements

- Initially, you should implement the design as close as possible to the mockup. Later, you might choose to fit your personality/style.

- **Note**: You should complete at least the tasks given for _explorer_ mode as listed below before turning in the assignment, as well as before attempting _adventure_ or _epic_ modes.

### Explorer Mode

- [x] Recreate the page as closely as you possibly can. Use the same fonts, sizes, and colors.
- [x] Make sure the site is responsive.
- [x] Deploy your site

### Adventure Mode

- [ ] Take the time to personalize the site with information about yourself, links to your projects, and your pictures.
- [ ] Keep it professional, but make it your own.

### Epic Mode
- [ ] Go back and work on the adventure or epic mode for a past assignment.
- [ ] Start to research [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript)

**Comment by TatyCat** [comment]
https://github.com/TatyCat/jasonfolio 

Challenging but I learned more about Flexbox.

**Comment by mdewey** [comment]
Your homework was marked: **Exceeds Expectations**

![Woooooh!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBTUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--51a35f0aa3861c6c972e89ad3572a7cc7ad26dba/exceeds-1.gif)
> &ldquo;Woooooh!&rdquo;
__&mdash; via **[Mark Dewey](https://gifs.suncoast.io/venerations/63)**__
